### PR TITLE
Also test built image

### PR DESCRIPTION
**Pull request by Al2Klimov**
... via icinga2 daemon -C.

Not to accidentally miss new dependencies.

### CODE REVIEW

**Comment by Al2Klimov** [comment]
E.g. Boost Stacktrace.

**Comment by julianbrost** [comment]
Shouldn't this also be run by `build.bash` and for PRs in this repo?

**Comment by julianbrost** [comment]
Now that I think about this, we recently (with UoM parsing) had the situation where the tests would fail but the image was still pushed to Docker Hub. So I think it would make sense to additionally run `make test`.

**Comment by Al2Klimov** [comment]
The script already runs `make test`.

**Comment by julianbrost** [comment]
Well, yes and no, there's indeed a call to `make test`, but it doesn't work:
```
+ make test
Running tests...
Test project /i2cp/build
No tests were found!!!
```

**Comment by Al2Klimov** [comment]
... and we should definitively address that construction area as well.

**Review by julianbrost — APPROVED** [review]
Removing something from https://github.com/Icinga/docker-icinga2/blob/ccd8cce1860c8baa473e4ffeeb78efd446012573/deps.Dockerfile#L62 gives
```
/usr/lib/x86_64-linux-gnu/icinga2/sbin/icinga2: error while loading shared libraries: libboost_regex.so.1.67.0: cannot open shared object file: No such file or directory
```
and `build.bash` exists with code 127.

**Pull request merged**
