### PR TITLE
Add license headers

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by Al2Klimov** [comment]
Borrowed from https://github.com/torvalds/linux/blob/master/drivers/accessibility/braille/braille_console.c

**Comment by Al2Klimov** [comment]
*bump*

**Comment by lippserd** [comment]
Please use something that matches the format we use in all other projects as well, e.g.
> Icinga 2 Docker | (c) 2020 Icinga GmbH | GPLv2+

**Review by lippserd — CHANGES_REQUESTED** [review]
Please see above.

**Review by lippserd — APPROVED** [review]

**Review by N-o-X — APPROVED** [review]

**Pull request merged**
