### PR TITLE
Ship SSMTP

### LINKED ISSUE #41: Add possibility to send mail notifications from the container
Hi,

I am currently evaluating a Icinga 2 docker setup. During my evaluation I came across the topic _mail notification_, currently I see no possibility to send such from a container based on this image. Is it possible to add this feature?

I found a icinga2 docker image which has this possibility, the image integrated `msmtp` to send mails:

https://github.com/jjethwa/icinga2#sending-notification-mails

Thanks and best regards
Michael

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #41

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Blocked by

* [ ] #50
* [ ] Icinga/icinga2#8623

**Comment by bodsch** [comment]
SSMTP is not anymore in Debian Repos.
msmtp should be used instead.
see https://github.com/bodsch/docker-icinga2/pull/62

**Comment by Al2Klimov** [comment]
It **is**: https://packages.debian.org/en/bullseye/ssmtp

**Comment by mcktr** [comment]
@Al2Klimov It is **not**. You are referring to Debian bullseye, which is currently the testing branch of Debian. The package `ssmtp` is not included in the current stable branch buster. Mixing packages from various releases is not a good idea, it can lead to a _FrankenDebian_, 

* https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

Furthermore the package `ssmtp` is currently not maintained. 

* https://tracker.debian.org/pkg/ssmtp
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=925056
* https://wiki.debian.org/sSMTP

As @bodsch already suggested `msmtp` should be used as an alternative, it is maintained and is included in the stable branch buster.

* https://packages.debian.org/source/buster/msmtp 
* https://tracker.debian.org/pkg/msmtp

Best regards
Michael

**Comment by Al2Klimov** [comment]
A valid argument. _My_ plan was to do so until bullseye becomes stable.

**Comment by mcktr** [comment]
Then `ssmtp` is still unmaintained. The latest changes to the `ssmtp` package are "only" QA uploads, from the Debian QA Group.

* https://tracker.debian.org/news/1123058/accepted-ssmtp-264-9-source-into-unstable/
* https://tracker.debian.org/news/1227435/accepted-ssmtp-264-10-source-into-unstable/

Why using `ssmtp` when there is a maintained alternative? Where do you see the benefit of `ssmtp` over `msmtp`?

Best regards
Michael

**Comment by Al2Klimov** [comment]
I’ve consulted multiple sources and it was the most recommended one.

**Comment by mcktr** [comment]
Well, even the wiki page you link to says its currently not maintained. 

* https://wiki.archlinux.org/index.php/SSMTP

This may raises support questions from users why the Icinga 2 Docker image uses unmaintained software. Also consider that in some enterprise environments you are not allowed to use unmaintained software.

`msmtp` is also `sendmail` compatible, so changes to the notifications scripts shouldn't be necessary.

* https://marlam.de/msmtp/

Best regards
Michael

**Comment by dwt** [comment]
I would like to second this opinion - please use maintained software in the image. I.e. software where the whole burden of maintaining it its not on the system integrators at Debian.

**Comment by dwt** [comment]
@Al2Klimov if I can help in this pull request to get msmtp configured - please let me know.

**Pull request closed without merging**
