### PR TITLE
check_icmp: escalate privileges via setuid

### LINKED ISSUE #47: Not able to run check_icmp: Failed to optain ICMP socket
Hi,

I am facing the following situation on a fresh Icinga 2 docker container (tag: `2.13.3`).

```
sudo docker run -ti -h i2m1 -p 5666:5665 icinga/icinga2:2.12.3 bash

[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Initializing /data as we're the init process (PID 1)
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Checking "/data/etc/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Copying "/data-init/etc/icinga2" to "/data/etc/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Checking "/data/var/cache/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Copying "/data-init/var/cache/icinga2" to "/data/var/cache/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Checking "/data/var/lib/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Copying "/data-init/var/lib/icinga2" to "/data/var/lib/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Checking "/data/var/log/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Copying "/data-init/var/log/icinga2" to "/data/var/log/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Checking "/data/var/run/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Copying "/data-init/var/run/icinga2" to "/data/var/run/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Checking "/data/var/spool/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Copying "/data-init/var/spool/icinga2" to "/data/var/spool/icinga2"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Checking "/var/lib/icinga2/certs/ca.crt"
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Looking up "dumb-init" in $PATH
[2021-01-21 10:42:54 +0000] information/DockerEntrypoint: Running "/usr/bin/dumb-init"      
icinga@i2m1:/$ /usr/lib/nagios/plugins/check_icmp -H 127.0.0.1
check_icmp: Failed to obtain ICMP socket: Operation not permitted
```

From a quick research this is caused by missing permission for the user. I don't know if other plugins are also affected, but I can tell that check_ping works fine for example. 

```
icinga@i2m1:/$ /usr/lib/nagios/plugins/check_ping -H 127.0.0.1 -w 10,10% -c 20,20%
PING OK - Packet loss = 0%, RTA = 0.06 ms|rta=0.063000ms;10.000000;20.000000;0.000000 pl=0%;10;20;0
```

Best regards
Michael

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #47
closes #49

### CODE REVIEW

**Comment by Al2Klimov** [comment]
## Before/after

```
➜  docker-icinga2 git:(master) ✗ docker run --rm -it --entrypoint '' icinga/icinga2:master /usr/lib/nagios/plugins/check_icmp -H 127.0.0.1
check_icmp: Failed to obtain ICMP socket: Operation not permitted
➜  docker-icinga2 git:(master) ✗ docker run --rm -it --entrypoint '' --user 0 icinga/icinga2:master /usr/lib/nagios/plugins/check_icmp -H 127.0.0.1
OK - 127.0.0.1: rta 0.012ms, lost 0%|rta=0.012ms;200.000;500.000;0; pl=0%;40;80;; rtmax=0.039ms;;;; rtmin=0.005ms;;;;
➜  docker-icinga2 git:(master) ✗ docker run --rm -it --entrypoint '' icinga/icinga2 /usr/lib/nagios/plugins/check_icmp -H 127.0.0.1
OK - 127.0.0.1: rta 0.012ms, lost 0%|rta=0.012ms;200.000;500.000;0; pl=0%;40;80;; rtmax=0.039ms;;;; rtmin=0.004ms;;;;
➜  docker-icinga2 git:(master) ✗
```

**Comment by mcktr** [comment]
@Al2Klimov Thanks for fixing the issue. :+1: What wonders me is why the following works just fine:

```
# vim Dockerfile

FROM debian:buster-slim

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update; apt-get install -y \
	monitoring-plugins

RUN ["adduser", "--system", "--group", "--home", "/var/lib/icinga2", "--disabled-login", "--force-badname", "--no-create-home", "--uid", "5665", "icinga"]

USER icinga

CMD ["bash"]

# sudo docker build -t testing:latest .
# sudo docker run -ti testing:latest bash
icinga@dd0819f47a5c:/$ /usr/lib/nagios/plugins/check_icmp -H 127.0.0.1
OK - 127.0.0.1: rta 0.040ms, lost 0%|rta=0.040ms;200.000;500.000;0; pl=0%;40;80;; rtmax=0.095ms;;;; rtmin=0.025ms;;;; 
```

Why is there a different behavior form this custom Dockerfile and the Icinga 2 container? AFAIK the Icinga 2 Dockerfile uses also `debian:buster-slim` as base image. 

Best regards
Michael

**Comment by Al2Klimov** [comment]
🤷‍♂️

**Comment by mcktr** [comment]
I did a little investigation on this problem. Instead of fixing the symptom I would prefer to actually fix the root cause. 

The problem is caused by a missing package which will not be installed since `--no-install-{recommends,suggests}` is set. The missing package in question is `libcap2-bin` which is marked as `recommends` on the `monitoring-plugins-basic` package. The `libcap` package implements the user-space interfaces to the POSIX 1003.1e capabilities available in Linux kernels

- https://packages.debian.org/en/stretch/monitoring-plugins-basic
- https://packages.debian.org/stretch/libcap2-bin

# Test

## not working

```
# vim Dockerfile

FROM debian:buster-slim

ENV DEBIAN_FRONTEND noninteractive

RUN ["/bin/bash", "-exo", "pipefail", "-c", "apt-get update; apt-get install --no-install-{recommends,suggests} -y monitoring-plugins" ]

RUN ["adduser", "--system", "--group", "--home", "/var/lib/icinga2", "--disabled-login", "--force-badname", "--no-create-home", "--uid", "5665", "icinga"]

USER icinga

CMD ["bash"]

# sudo docker build -t testing:latest .
# sudo docker run -ti testing:latest bash
icinga@36fb45255013:/$ /usr/lib/nagios/plugins/check_icmp -H 127.0.0.1
check_icmp: Failed to obtain ICMP socket: Operation not permitted
```

## working

```
# vim Dockerfile

FROM debian:buster-slim

ENV DEBIAN_FRONTEND noninteractive

RUN ["/bin/bash", "-exo", "pipefail", "-c", "apt-get update; apt-get install --no-install-{recommends,suggests} -y monitoring-plugins libcap2-bin" ]

RUN ["adduser", "--system", "--group", "--home", "/var/lib/icinga2", "--disabled-login", "--force-badname", "--no-create-home", "--uid", "5665", "icinga"]

USER icinga

CMD ["bash"]


# sudo docker build -t testing:latest .
# sudo docker run -ti testing:latest bash
icinga@9df718170d20:/$ /usr/lib/nagios/plugins/check_icmp -H 127.0.0.1
OK - 127.0.0.1: rta 0.041ms, lost 0%|rta=0.041ms;200.000;500.000;0; pl=0%;40;80;; rtmax=0.099ms;;;; rtmin=0.025ms;;;; 
```

Since I don't know if other check plugins rely on the `libcap` package and we really can't say it for the plugins out in the _wild_ I would suggest to add the missing package to the container image.

Best regards
Michael

**Comment by Al2Klimov** [comment]
Nice one! Please open a PR. (Just add this particular package.)

**Pull request closed without merging**
